version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 25
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
exclude_patterns:
- "cypress/{integration,support}/*.js"
- "src/*.test.*"
- "src/app/{components,containers,contexts}/**/*.test.*"
- "src/app/{containers}/ConsentBanner/**/*.test.*"
- "src/app/{containers}/PageViewAnalytics/**/*.test.*"
- "src/app/{dataValidator}/{helpers,utilities}/**/*.test.*"
- "src/app/{dataValidator}/**/*.test.*"
- "src/app/helpers/*.test.*"
- "src/app/helpers/{json}/*.test.*"
- "src/app/helpers/{storybook}/**/*.test.*"
- "src/app/Layouts/*.test.*"
- "src/app/lib/*.test.*"
- "src/app/lib/**/*.test.*"
- "src/app/lib/**/**/*.test.*"
- "src/app/lib/**/**/**/*.test.*"
- "src/app/models/*.test.*"
- "src/app/models/**/**/*.test.*"
- "src/app/routes/*.test.*"
- "src/app/routes/**/*.test.*"
- "src/app/routes/**/**/*.test.*"
- "src/server/*.test.*"
- "src/server/{assets,Document}/*.test.*"

