version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - apt update
      - apt -y install libgconf2-4   # needed for older cypress/bbc-a11y
      - npm ci
  pre_build:
    commands:
      - npm run build
  build:
    commands:
      - npx apache2-license-checker
      - # npx chromatic test run ... (not yet implemented)
      - npm run test:local
      - # ./cc-test-reporter ... (not yet implemented)
      - npm run test:ci
