name: Simorgh CI - Unit Tests & Code Coverage
on:
  push:
    branches:
      - '**'
      - '!latest'
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      CI: true
      LOG_LEVEL: 'error'
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install & Build Simorgh
        run: |
          npm ci
          npm run build

      - name: Setup Code Climate Test Coverage
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter	
          chmod +x ./cc-test-reporter	
          ./cc-test-reporter before-build

      - name: Unit Tests
        run: npm run test:unit

      - name: Report Code Climate Test Coverage
        run: ./cc-test-reporter after-build -t lcov --debug --exit-code 0
