name: Simorgh CI - Unit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npx apache2-license-checker
        npm test
      env:
        CI: true

  cypress-run:
    runs-on: ubuntu-latest
    # let's make sure our tests pass on Chrome browser
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run Cypress
        uses: cypress-io/github-action@v1
        with:
          start: npm run start
          browser: chrome
          headless: true
        env: CYPRESS_SKIP_EU=true
        
